### PR TITLE
add CPU and memory panels to all servers Grafana dashboard

### PR DESCRIPTION
**Pull request by greenstatic**
Closes: #27

### CODE REVIEW

**Comment by greenstatic** [comment]
@pcslayer2801 do you mind testing this out?

**Comment by pcslayer2801** [comment]
ich hab es getestet. es sieht genau so aus wie wir dachten, das es aussehen koennte.
nur eine frage: bei mir wird nur eine linie in dem grafen angezeigt ':node-exporter:9100 (node_exporter)' 
soll das so sein? oder sollten da mehrere Linien quasi pro server eine?

**Comment by greenstatic** [comment]
> I tested it. It looks exactly like we thought it would look.
> just one question: i only have one line in the graph ':node-exporter:9100 (node_exporter)'
> should that be so? or should there be several lines per server?

There should be a line (or rather an entry in the legend) per node_exporter/netdata instance. So if I understand correctly; you have multiple instances, which you can see in the server instance dashboard but not in the all servers cpu and ram panel?

**Comment by pcslayer2801** [comment]
> > I tested it. It looks exactly like we thought it would look.
> > just one question: i only have one line in the graph ':node-exporter:9100 (node_exporter)'
> > should that be so? or should there be several lines per server?
> 
> There should be a line (or rather an entry in the legend) per node_exporter/netdata instance. So if I understand correctly; you have multiple instances, which you can see in the server instance dashboard but not in the all servers cpu and ram panel?

exactly that is the point :)

**Comment by greenstatic** [comment]
Do you have the correct job selected (top left corner of the dashboard)?

I assume you have node_exporter and not Netdata.

If you go to explore (left menu) and enter the following query:
```
sum(node_cpu_seconds_total) by (instance)
```
How many different time series (legend entries) do you have?

**Comment by pcslayer2801** [comment]
> Do you have the correct job selected (top left corner of the dashboard)?

yes i did
> 
> I assume you have node_exporter and not Netdata.

that is correct
> 
> If you go to explore (left menu) and enter the following query:
> 
> ```
> sum(node_cpu_seconds_total) by (instance)
> ```
> 
> How many different time series (legend entries) do you have?

just one

**Comment by greenstatic** [comment]
How many do you expect?

**Comment by pcslayer2801** [comment]
I don't know if this can be helpful:
we have 2 bbb servers; on each of them runs the bbb-exporter; on another server I have installed prometheues, according to your instructions, and Grafana. This is all going great too :)


> How many do you expect?

one per server ? i thought

**Comment by greenstatic** [comment]
So you expect two time series (2 BBB servers). Do both of them have the same job name?

**Comment by pcslayer2801** [comment]
> So you expect two time series (2 BBB servers). Do both of them have the same job name?

job name in prometheues? both named bbb

**Comment by pcslayer2801** [comment]
wait, i think i know where i got the misunderstanding ... your bbb-exporter only returns the bbb-api stuff ... of course no cpu and ram load of the server, i have to return this seperately and then embed it in prometheues right?

**Comment by greenstatic** [comment]
bbb-exporter only returns bbb metrics, correct. The CPU & RAM metrics are gathered by either node_exporter or Netdata. For the all servers dashboard to display CPU & RAM utlization of ALL your bbb servers, the job name of the appropriate target needs to be the same. This can be achieved if you have 1 target for node_exporter / Netdata and simply add your servers to the target field - similar to this: https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#8-add-the-exporter-to-your-prometheus-configuration.

**Comment by pcslayer2801** [comment]
> bbb-exporter only returns bbb metrics, correct. The CPU & RAM metrics are gathered by either node_exporter or Netdata. For the all servers dashboard to display CPU & RAM utlization of ALL your bbb servers, the job name of the appropriate target needs to be the same. This can be achieved if you have 1 target for node_exporter / Netdata and simply add your servers to the target field - similar to this: https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#8-add-the-exporter-to-your-prometheus-configuration.

now I understand :)

i installed node exporter on both servers and they both shown in the dashboard *-* 

THANK YOU VERY MUCH !

**Comment by greenstatic** [comment]
Great so everything works and I can merge this into master?

**Comment by pcslayer2801** [comment]
> Great so everything works and I can merge this into master?

Yeah, I think so.
Thanks a lot for your support :+1:

**Pull request merged**
